{
 "title": "Application Stats",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Key Create",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "integral(stats.KeyCreateAPI)" }
   ]
  },
  {
   "title": "Signing",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "integral(stats.SignAPI)" }
   ]
  },
  {
   "title": "Verify",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "integral(stats.VerifyAPI)" }
   ]
  },
  {
   "title": "Encrypt",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "integral(stats.EncryptAPI)" }
   ]
  },
  {
   "title": "Success Key Create",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "target": "integral(stats.KeyCreateAPI)" }
   ]
  },
  {
   "title": "Success Signed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "max",
   "targets": [
    { "target": "integral(stats.SignAPI)" }
   ]
  },
  {
   "title": "Success Verified",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "integral(stats.VerifyAPI)" }
   ]
  },
  {
   "title": "BackEnd Errors",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "integral(stats.backend_error)" }
   ]
  },
  {
   "title": "Success Encrypt",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "integral(stats.EncryptAPI)" }
   ]
  },
  {
   "title": "Success Decrypt",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "integral(stats.DecryptAPI)" }
   ]
  }
 ]
}