{
 "title": "advtcloud-vm-4",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Memory Containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "collectd.advtcloud-vm-4.docker-django.memory_usage.total"
    },
    {
     "target": "collectd.advtcloud-vm-4.docker-load_balancer.memory_usage.total"
    },
    {
     "target": "collectd.advtcloud-vm-4.docker-postgres.memory_usage.total"
    },
    {
     "target": "collectd.advtcloud-vm-4.docker-web_services.memory_usage.total"
    }
   ]
  },
  {
   "title": "Host Disk Space % Free",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectd.advtcloud-vm-4.df-root.percent_bytes-free"
    }
   ]
  },
  {
   "title": "Host Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "collectd.advtcloud-vm-4.memory.memory-free"
    }
   ]
  },
  {
   "title": "ADV processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectd.advtcloud-vm-4.processes-advhsm.ps_count.processes"
    },
    {
     "target": "collectd.advtcloud-vm-4.processes-ra_slave.ps_count.processes"
    },
    {
     "target": "collectd.advtcloud-vm-4.processes-rpyc.ps_count.processes"
    }
   ]
  },
  {
   "title": "CPU usage container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "collectd.advtcloud-vm-4.docker-django.cpu_percent"
    },
    {
     "target": "collectd.advtcloud-vm-4.docker-load_balancer.cpu_percent"
    },
    {
     "target": "collectd.advtcloud-vm-4.docker-postgres.cpu_percent"
    },
    {
     "target": "collectd.advtcloud-vm-4.docker-web_services.cpu_percent"
    }
   ]
  },
  {
   "title": "TCP connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectd.advtcloud-vm-4.tcpconns-443-local.*"
    },
    {
     "target": "collectd.advtcloud-vm-4.tcpconns-443-local.tcp_connections-ESTABLISHED"
    }
   ]
  }
 ]
}